'use client';
import { useEffect, useState } from 'react';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { auth, db } from '../../lib/firebase';
import { useRouter } from 'next/navigation';
import { collection, getDocs, orderBy, query, limit, where } from 'firebase/firestore';
import { callApi } from '../../lib/api';

const fmt = (v:any) => { if(!v) return '—'; const d=v?.toDate?v.toDate():new Date(v); return Number.isNaN(d.getTime())?'—':d.toLocaleString(); };
export default function Admin(){
 const [u,setU]=useState<any>(null),[tab,setTab]=useState('overview'),[users,setUsers]=useState<any[]>([]),[licenses,setLicenses]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[packages,setPackages]=useState<any[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState<any>({email:'',credits:100,deviceLimit:1,expiresDays:30}),[creditForm,setCreditForm]=useState<any>({licenseId:'',amount:10,reason:'Manual adjustment'}),[pkg,setPkg]=useState<any>({name:'',credits:100,price:5,currency:'USD'}),[costs,setCosts]=useState<any>({pdf_processing:2,data_generation:2});
 const router=useRouter();
 async function load(){
  const [us,ls,ps,cs]=await Promise.all([
   getDocs(query(collection(db,'users'),orderBy('createdAt','desc'),limit(100))),
   getDocs(query(collection(db,'licenses'),orderBy('createdAt','desc'),limit(100))),
   getDocs(query(collection(db,'payments'),orderBy('createdAt','desc'),limit(100))),
   getDocs(query(collection(db,'creditPackages'),orderBy('sort','asc')))
  ]);
  setUsers(us.docs.map(d=>({id:d.id,...d.data()})));setLicenses(ls.docs.map(d=>({id:d.id,...d.data()})));setPayments(ps.docs.map(d=>({id:d.id,...d.data()})));setPackages(cs.docs.map(d=>({id:d.id,...d.data()})));
 }
 useEffect(()=>onAuthStateChanged(auth,async x=>{if(!x){router.replace('/login');return;} const token=await x.getIdTokenResult(true); if(!token.claims.admin && x.email !== 'sajolsarker5789@gmail.com'){setError('Admin access is not enabled for this account.');return;} setU(x);try{await load()}catch(e:any){setError(e.message||'Could not load admin data.')} }),[router]);
 async function bootstrap(){setBusy(true);setError('');setNotice('');try{const r=await callApi('/admin/bootstrap',{});setNotice(r.message||'Admin enabled.');await auth.currentUser?.getIdToken(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function updateCosts(e:any){e.preventDefault();setBusy(true);setError('');try{const r=await callApi('/admin/credit-costs',costs);setCosts(r.costs);setNotice('Credit costs updated.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function createLicense(e:any){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await callApi('/admin/license/create',form);setNotice(r.message||'License created.');setForm({...form,email:'',credits:100,deviceLimit:1,expiresDays:30});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function adjust(e:any){e.preventDefault();setBusy(true);try{const r=await callApi('/admin/license/credits',creditForm);setNotice(r.message||'Credits updated.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function toggle(l:any){setBusy(true);try{await callApi('/admin/license/status',{licenseId:l.id,status:l.status==='active'?'blocked':'active'});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function resetDevice(l:any){setBusy(true);try{await callApi('/admin/device/reset',{licenseId:l.id});setNotice('Device activations reset.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function createPackage(e:any){e.preventDefault();setBusy(true);try{await callApi('/admin/package/save',pkg);setNotice('Package saved.');setPkg({name:'',credits:100,price:5,currency:'USD'});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function payment(id:string,status:string){setBusy(true);try{await callApi('/admin/payment/status',{paymentId:id,status});setNotice(`Payment ${status}.`);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!u) return <main className="wrap"><div className="card"><h1>Admin Console</h1><p className="muted">{error||'Checking admin access…'}</p></div></main>;
 return <><nav className="nav"><div className="brand">Visa Autofill Pro — Admin</div><button className="btn secondary" onClick={()=>signOut(auth)}>Sign out</button></nav><main className="wrap"><div className="pageHead"><div><h1>Admin Console</h1><p className="muted">Manage customers, licenses, credits, devices, packages and payments.</p></div></div>{error&&<div className="alert errorBox">{error}</div>}{notice&&<div className="alert successBox">{notice}</div>}<div className="adminToolbar"><span className="muted">Signed in as {u.email}</span><button className="miniBtn" onClick={bootstrap} disabled={busy}>Refresh admin access</button></div>
 <div className="tabs">{['overview','licenses','credits','payments','packages','users','settings'].map(x=><button className={tab===x?'tab active':'tab'} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
 {tab==='overview'&&<div className="grid statsGrid"><div className="card"><div className="muted">Users</div><div className="stat">{users.length}</div></div><div className="card"><div className="muted">Active licenses</div><div className="stat">{licenses.filter(x=>x.status==='active').length}</div></div><div className="card"><div className="muted">Credits in licenses</div><div className="stat">{licenses.reduce((a,x)=>a+Number(x.credits||0),0)}</div></div><div className="card"><div className="muted">Pending payments</div><div className="stat">{payments.filter(x=>x.status==='pending').length}</div></div></div>}
 {tab==='licenses'&&<><section className="card"><h2>Create license</h2><form className="formGrid" onSubmit={createLicense}><input className="input" placeholder="Customer email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input className="input" type="number" placeholder="Credits" value={form.credits} onChange={e=>setForm({...form,credits:Number(e.target.value)})}/><input className="input" type="number" placeholder="Device limit" value={form.deviceLimit} onChange={e=>setForm({...form,deviceLimit:Number(e.target.value)})}/><input className="input" type="number" placeholder="Expires in days" value={form.expiresDays} onChange={e=>setForm({...form,expiresDays:Number(e.target.value)})}/><button className="btn" disabled={busy}>Create license</button></form></section><section className="card" style={{marginTop:18}}><h2>Licenses</h2><div className="tableWrap"><table className="table"><thead><tr><th>Key</th><th>User</th><th>Status</th><th>Credits</th><th>Devices</th><th>Expiry</th><th>Actions</th></tr></thead><tbody>{licenses.map(l=><tr key={l.id}><td><code>{l.licenseKey}</code></td><td>{l.userEmail||l.userId||'—'}</td><td>{l.status}</td><td>{l.credits}</td><td>{l.deviceLimit}</td><td>{fmt(l.expiresAt)}</td><td className="row"><button className="miniBtn" onClick={()=>toggle(l)}>{l.status==='active'?'Block':'Unblock'}</button><button className="miniBtn" onClick={()=>resetDevice(l)}>Reset devices</button><button className="miniBtn" onClick={async()=>{const v=prompt('New device limit',String(l.deviceLimit||1));if(v)try{await callApi('/admin/license/device-limit',{licenseId:l.id,deviceLimit:Number(v)});setNotice('Device limit updated.');await load()}catch(e:any){setError(e.message)}}}>Device limit</button></td></tr>)}</tbody></table></div></section></>}
 {tab==='credits'&&<section className="card"><h2>Adjust license credits</h2><form className="formGrid" onSubmit={adjust}><select className="input" value={creditForm.licenseId} onChange={e=>setCreditForm({...creditForm,licenseId:e.target.value})} required><option value="">Select license</option>{licenses.map(l=><option key={l.id} value={l.id}>{l.licenseKey} — {l.credits} credits</option>)}</select><input className="input" type="number" value={creditForm.amount} onChange={e=>setCreditForm({...creditForm,amount:Number(e.target.value)})}/><input className="input" value={creditForm.reason} onChange={e=>setCreditForm({...creditForm,reason:e.target.value})}/><button className="btn" disabled={busy}>Apply adjustment</button></form></section>}
 {tab==='payments'&&<section className="card"><h2>Payment requests</h2><div className="tableWrap"><table className="table"><thead><tr><th>User</th><th>Package</th><th>Amount</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{p.userEmail}</td><td>{p.packageName}</td><td>{p.currency} {p.amount}</td><td>{p.status}</td><td>{fmt(p.createdAt)}</td><td>{p.status==='pending'&&<div className="row"><button className="miniBtn" onClick={()=>payment(p.id,'approved')}>Approve</button><button className="miniBtn dangerBtn" onClick={()=>payment(p.id,'rejected')}>Reject</button></div>}</td></tr>)}</tbody></table></div></section>}
 {tab==='packages'&&<><section className="card"><h2>Create / update package</h2><form className="formGrid" onSubmit={createPackage}><input className="input" placeholder="Package name" value={pkg.name} onChange={e=>setPkg({...pkg,name:e.target.value})} required/><input className="input" type="number" placeholder="Credits" value={pkg.credits} onChange={e=>setPkg({...pkg,credits:Number(e.target.value)})}/><input className="input" type="number" step="0.01" placeholder="Price" value={pkg.price} onChange={e=>setPkg({...pkg,price:Number(e.target.value)})}/><input className="input" placeholder="Currency" value={pkg.currency} onChange={e=>setPkg({...pkg,currency:e.target.value})}/><button className="btn">Save package</button></form></section><section className="card" style={{marginTop:18}}><h2>Packages</h2>{packages.map(p=><div className="packageRow" key={p.id}><strong>{p.name}</strong><span>{p.credits} credits</span><span>{p.currency} {p.price}</span><span>{p.active?'Active':'Inactive'}</span></div>)}</section></>}
 {tab==='settings'&&<section className="card"><h2>Credit costs</h2><p className="muted">These values control how many credits one extension operation consumes.</p><form className="formGrid" onSubmit={updateCosts}><label>PDF processing<input className="input" type="number" min="1" value={costs.pdf_processing} onChange={e=>setCosts({...costs,pdf_processing:Number(e.target.value)})}/></label><label>Data generation<input className="input" type="number" min="1" value={costs.data_generation} onChange={e=>setCosts({...costs,data_generation:Number(e.target.value)})}/></label><button className="btn" disabled={busy}>Save credit costs</button></form></section>}
 {tab==='users'&&<section className="card"><h2>Users</h2><div className="tableWrap"><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Created</th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td>{x.name||'—'}</td><td>{x.email}</td><td>{x.status}</td><td>{fmt(x.createdAt)}</td></tr>)}</tbody></table></div></section>}
 </main></>;
}
